### ISSUE TITLE
update to 1.1 lost data

### ISSUE THREAD

**Issue by rkgeorge** [Microsoft/Bing-Maps-Fleet-Tracker#9] opened 2018-02-12 21:27 UTC
update 1.1 button on our fleet tracker demo .azurewebsites.net
1) Clicking the link gave a 404 error
2) Using doc update process for updating existing deployment from deployment portal
   a. After update completed first time - Open Website link failed
   b. After update completed second time - Open Website link worked but all the previous data was lost

Note there are now two hurghada SQL databases showing in the owner Azure Dashboard. I'm guessing one of these holds the previous data but a new one is now connected to the demo fleet tracker. 
Not sure what happened in this case.

**Comment by momohs** [comment] 2018-02-12 21:48
I'm looking for the root cause of this, does your deployment name include a dash "-" ?

**Comment by momohs** [comment] 2018-02-13 15:40
@rkgeorge we found a bug in our update script and got it fixed, if you try using the doc process for updating existing deployments one more time, you should get your data back.

After doing so, please feel free to go ahead and delete the database server starting with "namedbserver" and the storage account starting with "namestore" from your resource group on the Azure portal. They were created by mistake.

Note: newly created data on the wrong database will be lost.

**Comment by momohs** [comment] 2018-02-16 09:32
I'll close this issue for now. Please feel free to re-open if you still have any problems.

**Closed by momohs** 2018-02-16 09:32 UTC
